apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
      - name: student-api
        image: cyrilbaah/student-api
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "1"
          requests:
            memory: "600Mi"
            cpu: "750m"
        ports:
          - containerPort: 8000
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: student-api-secret
                key: SECRET_KEY
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: DEBUG
          - name: USE_S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: USE_S3_BUCKET
          - name: DB_TYPE
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: DB_TYPE
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: student-api-secret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: student-api-configmap
                key: DB_PORT

         